### ISSUE TITLE
Problem with the proxy.

### ISSUE THREAD

**Issue by patriksjalkds** [ex0dus-0x/brut3k1t#40]
dear ex0dus-0x,

the instagram bruteforce says after 20 attempts: Timeout Raised! i think that  my ip got blocked. 
can i fix it by adding proxy ips into the proxy.txt file? and how do i do that? sorry for my bad english :)

**Comment by ex0dus-0x** [comment]
Timeout raised is implemented since Instagram imposes a rate limit that stops you from logging in to the service, even if you give the right password. This basically means that brut3k1t waits until 5 minutes later, the program continues and enables you to run. I am trying to circumvent this, but this is what it is for now.

**Comment by patriksjalkds** [comment]
ok thanks! can you let me know when you fixed it?

**Comment by patriksjalkds** [comment]
sorry if i asking but....
is there a faster way to hack a instagram account?

**Comment by ex0dus-0x** [comment]
If you are going to use brut3k1t to hack other people, get out. I wrote brut3k1t as open source software for security enthusiasts and pentesters. i despise people who want to solely utilize it to hack other people. 

Please don't give me the "I'm just recovering my old account" or "I'm helping a friend" crap. I don't want to hear it.
