### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alideni78** [ex0dus-0x/brut3k1t#43]
read read me all did both of the sudo apt-get install python-pip & sudo pip install -r requirements.txt
but i get Traceback (most recent call last):
File "brut3k1t.py", line 2, in
from src.mainLib import *
File "/root/Desktop/brut3k1t-master/src/mainLib.py", line 24, in
import smtplib, argparse, paramiko, mechanize
File "/usr/local/lib/python2.7/dist-packages/paramiko/init.py", line 30, in
from paramiko.transport import SecurityOptions, Transport
File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 53, in
from paramiko.dsskey import DSSKey
File "/usr/local/lib/python2.7/dist-packages/paramiko/dsskey.py", line 27, in
from cryptography.hazmat.primitives.asymmetric.utils import (
ImportError: No module named utils
what i have to do?

**Comment by ex0dus-0x** [comment]
Rather than installing through `requirements.txt`, try running the `installer` as so.

    python extras/installer.py

I am currently working on a one-line installation build script with curl/wget. Stay tuned for that.

**Comment by KATRAX21** [comment]
man when i try to pip install it gives me this error

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting mechanize==0.2.5 (from -r requirements.txt (line 1))
  Could not fetch URL https://pypi.python.org/simple/mechanize/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement mechanize==0.2.5 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for mechanize==0.2.5 (from -r requirements.txt (line 1))
